[package]
name = "rpg-rs"
version = "0.1.0"
authors = ["carnoxen <carnoxen@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
